Cleaning up more algorithms
aimacode/aima-java pull request #309
Opened 2017-04-02 17:02 UTC by manu4rhyme

Added isGoalState() helper methods (and some more minor changes) , to align with the pseudo-code better.

2017-04-02 21:52 UTC, ctjoreilly requested changes
Please address the comments and then squash/rebase as needed.

Thanks

Ciaran

2017-04-02 21:52 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/informed/AStarSearch.java
>  		return searchController.solution(node);
Something similar could be done with searchController.solution(node) being replaced by solution(node). i.e.:

	public List<A> solution(Node<A, S> node) {
 		return searchController.solution(node);
 	}

2017-04-02 21:52 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/informed/RecursiveBestFirstSearch.java
> +	}
What if nodes has size() == 1?

2017-04-02 21:52 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/uninformed/GraphSearch.java
> +
It looks like you re-formatted the whole file. This makes it extremely difficult to review the changes. Please don't do this.

2017-04-03 00:49 UTC, manu4rhyme commented on core/src/main/java/aima/core/search/basic/informed/AStarSearch.java
>  		return searchController.solution(node);
Yes, I have already taken this into account. Also for searchController.failure(), nodeFactory.newRootNode() and nodeFactory.newChildNode()

2017-04-03 01:55 UTC, manu4rhyme commented on core/src/main/java/aima/core/search/basic/informed/RecursiveBestFirstSearch.java
> +	}
True, I overlooked this trivial test case.
Fixed.

2017-04-03 01:56 UTC, manu4rhyme commented on core/src/main/java/aima/core/search/basic/uninformed/GraphSearch.java
> +
Sorry, it was a white-space issue.
Fixed.

2017-04-03 01:57 UTC, manu4rhyme commented
@ctjoreilly Fixed

2017-04-03 03:39 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/informed/AStarSearch.java
>  		return searchController.solution(node);
but what about here at line 121 in AStartSearch?

2017-04-03 03:40 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/informed/RecursiveBestFirstSearch.java
> +	}
Nice and clean :)

2017-04-03 09:58 UTC, manu4rhyme commented on core/src/main/java/aima/core/search/basic/informed/AStarSearch.java
>  		return searchController.solution(node);
But , its inside the solution(node) helper function itself.

2017-04-03 13:49 UTC, ctjoreilly commented on core/src/main/java/aima/core/search/basic/informed/AStarSearch.java
>  		return searchController.solution(node);
My bad! :) the code collapsing through me off

2017-04-03 13:54 UTC, merged