Add Markov Decision Process to AIMA4e
aimacode/aima-java pull request #386
Opened 2018-03-21 20:48 UTC by ritwik12

Solves #188.
This PR consists:
1. Readme.md edit to add Markov Decision Process
2. Add MarkovDecisionProcess.java - reimplemented for AIMA4e and improved java doc to make it more closer according to the third edition AIMA book page 647 chapter 17.

2018-03-22 11:48 UTC, utsavoza requested changes
Please do not simply copy the implementations of one branch to another. The currently implemented API is different on both the branches.

2018-03-22 12:19 UTC, ritwik12 commented
@utsavoza Those are abstract methods and they work same for both the branches. Also, I have used Agent in place of Action here. and changed the java doc according to the book. you are not making any suggestions here. but simply arguing.

2018-03-22 12:19 UTC, utsavoza commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
I am not sure how an action type extends an Agent?

2018-03-22 12:19 UTC, utsavoza commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> + * Artificial Intelligence A Modern Approach (3rd Edition): page 647.<br>
You are proposing changes to `AIMA4e` branch, the javadoc should reflect the change.

2018-03-22 12:19 UTC, utsavoza commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +	Set<Atype> ACTIONS(Stype s);
Please be consistent with existing naming conventions used throughtout the project.

2018-03-22 12:21 UTC, ritwik12 commented
@utsavoza and it's called a pull request because it's a "request", I am not pushing to merge this. if it's wrong it will not be merged.

2018-03-22 12:30 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +	Set<Atype> ACTIONS(Stype s);
here you are referring to ACTIONS?

2018-03-22 12:36 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> + * Artificial Intelligence A Modern Approach (3rd Edition): page 647.<br>
Corrected, thanks for the correction.

2018-03-22 12:45 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +	Set<Atype> ACTIONS(Stype s);
The ACTIONS name is according to the method name as mentioned in the book to make it more close to the pseudo code.

2018-03-22 12:45 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
we are not having Action in AIMA4e just like AIMA3e branch, for that, we need to create a new file or we could use the existing API. the best-suited solution was using Agent API of AIMA4e which does the work of Action.

2018-03-22 18:43 UTC, utsavoza commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
I would suggest you provide an implementation of the interface to justify the usage of Agent type.

2018-03-23 13:03 UTC, samagra14 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
I guess @utsavoza is right. And besides, I have mentioned earlier too that the APIs in both the branches are entirely different. Also, in the AIMA4e we use generics to represent actions.

2018-03-23 17:28 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
Thanks for your reviews @utsavoza  and @samagra14. I am still learning a lot of things. Can you guys suggest what can we use in place of Agent here to make it more compatible with AIMA4e?

2018-03-23 19:10 UTC, ritwik12 commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +public interface MarkovDecisionProcess<Stype, Atype extends Agent> {
I think we don't need Agent for its function and we can implement it like this to prevent confusion.

2018-03-24 16:51 UTC, ritwik12 commented
@utsavoza please close the review if it's done. Thanks

2018-03-26 19:58 UTC, ritwik12 commented
@norvig  please have a look.

2018-05-23 01:55 UTC, norvig commented on core/src/main/java/aima/core/Probability/MarkovDecisionProcess.java
> +	Set<Atype> ACTIONS(Stype s);
ACTIONS should be Actions

2018-05-23 08:21 UTC, ritwik12 commented
@norvig I have made the changes, please have a look now.

2019-05-17 11:05 UTC, samagra14 commented
The API has changed quite a lot.and this version seems incompatible to those. Hence closing this PR.

2019-05-17 11:05 UTC, closed without merging