Adds Informed Searches to Classical search notebook
aimacode/aima-java pull request #433
Opened 2018-07-23 19:41 UTC by jsuyash1514

2018-07-23 19:47 UTC, jsuyash1514 commented
This PR adds rest of the uninformed searches and all the informed search strategies and their demonstrations solving the 8 Puzzle problem in Classical Search Notebook.

2018-07-23 19:48 UTC, jsuyash1514 commented
@norvig Please have a look.

2018-08-24 04:16 UTC, samagra14 requested changes
There are a few grammatical errors in the notebook. The implementations look good. Please go through the notebook once and remove any possible grammatical errors.

2018-08-24 04:16 UTC, samagra14 commented on notebooks/ClassicalSearch.ipynb
> +      "\n",
Instead of printing out the result at every iteration, we should print it after skipping a few iterations, This will make the notebook compact.

2018-12-30 09:12 UTC, samagra14 approved these changes

2018-12-30 09:14 UTC, samagra14 commented
@norvig 
I have thoroughly reviewed this PR. This looks good to be merged. Please have a look.

2019-02-02 18:06 UTC, merged